GET http://localhost:3000
Accept: application/json
Content-Type: application/json

###
POST http://localhost:3000/logout
Accept: application/json
Content-Type: application/json

###
POST http://localhost:3000/login
Accept: application/json
Content-Type: application/json

###
POST http://localhost:3000/send-message
Accept: application/json
Content-Type: application/json

{
    "phone_number": "6282117694132",
    "message": "Hello world!"
}