services:
  server:
    restart: always
    build:
      context: .
    environment:
      NODE_ENV: production
      IS_DOCKER: true
      JWT_SECRET: "secret"
    ports:
      - 3000:3000
    volumes:
      - ./temp:/home/node/wwebjs/.wwebjs_auth:rw
      - ./temp:/home/node/wwebjs/.wwebjs_cache:rw
